### ISSUE TITLE
Engines declaration is incorrect.

### ISSUE THREAD

**Issue by wraithgar** [isaacs/resolve-import#4]
https://github.com/isaacs/resolve-import/blob/06a8b9a0245f84ee71218d9171faf4c73359eac0/src/resolve-import.ts#L6

https://nodejs.org/docs/latest-v20.x/api/module.html#moduleisbuiltinmodulename

This was added in `v18.6.0, v16.17.0`

**Comment by wraithgar** [comment]
By extension the `tap` engines declaration is also incorrect.

**Comment by lukekarrys** [comment]
@isaacs this came up because we really like testing in the lower bound of our supported engines, in this case `v16.14.0`.

would you be open to using a [userland](https://github.com/sindresorhus/builtin-modules) or vendored solution while tap still supports Node 16?

**Comment by isaacs** [comment]
Patch comin up

**Comment by isaacs** [comment]
Oh, you're asking if it'd be possible to float a patch to have a userland `Module.isBuiltin`?

Could npm just bump the minimum version from 16.14 to 16.17? How many requests per day does the registry get from 16.14 through 16.17? Seems like that might be pretty low impact at this point, no?

**Comment by lukekarrys** [comment]
@wraithgar was asking for the patch you just landed, thank you for that!

i was derailing the initial thread to ask if you would drop `Module.isBuiltin` in favor or a userland module (or just vendor the code).

> Could npm just bump the minimum version from 16.14 to 16.17? How many requests per day does the registry get from 16.14 through 16.17? Seems like that might be pretty low impact at this point, no?

This is definitely true, but I haven't looked at the numbers. My request is purely selfish in that it would allow us to use `tap@18` without changing our current testing setup or releasing any major versions.

Our alternatives would be:
- Not use tap@18 until we do our next engines change which is likely not for ~1yr. Not the end of the world, but tap@18 is pretty nice
- Not change our engines and change the lower bound of our testing from `16.14.0 -> `16.17.0` and `18.0.0 -> 18.6.0`. I like this setup since it allows me to never think about what language features I use. I can be sure CI will fail.
- Bump our engines. This would be major versions for us across the board. Versions are cheap, but since we just did major versions of everything about a month ago, they're not as cheap right now.

**Comment by isaacs** [comment]
It's not hard to polyfill. In fact, I probably will just to make it keep working in case anyone is using it with a node version that doesn't have it (since engines is strictly advisory in many cases, and warnings are unfortunately often ignored in exactly the scenarios where someone would be using a super old node version).

Question is just whether I do another release of tap and resolve-import to put the engines back to `>=16`.

**Comment by wraithgar** [comment]
Yeah let's not put a whole mountain of effort into this.  If engines are correct we'll figure it out on our end.  npm itself is already well ahead of this, its subdependencies will have to follow suit in order to use the latest tap.
